# Generated by Django 4.0 on 2022-03-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.CharField(max_length=100, verbose_name='Решение для УД')),
                ('action', models.CharField(max_length=100, verbose_name='Действия')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
            ],
        ),
    ]
