# Generated by Django 4.0 on 2022-03-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='status',
            field=models.CharField(choices=[('none', 'none'), ('treatment', 'В обработке'), ('connected', 'Подключено')], default='none', max_length=60, null=True, verbose_name='Статус'),
        ),
    ]
