# Generated by Django 4.0 on 2022-03-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_solution_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='solution',
        ),
        migrations.AddField(
            model_name='solution',
            name='authorID',
            field=models.CharField(blank=True, max_length=100, verbose_name='ИД автора'),
        ),
    ]
