# Generated by Django 4.0 on 2022-03-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_solution_solution_solution_authorid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='authorID',
        ),
    ]
