# Generated by Django 4.0 on 2022-03-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_solution_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='author',
            field=models.CharField(blank=True, max_length=100, verbose_name='ИД автора'),
        ),
    ]
