# Generated by Django 4.0 on 2022-03-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_connectedsolution_remove_solution_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.CharField(blank=True, max_length=100, verbose_name='ИД решении')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='ИД автора')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
            ],
        ),
    ]
